version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./services/chat-api/src/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./services/chat-api/
    volumes:
        - './services/chat-api:/src/app'
    ports:
        - '3000:3000'
    environment:
        - DATABASE_URL=postgres://admin:admin@users-db:5432/microchat_users_dev
        - DATABASE_TEST_URL=postgres://admin:admin@users-db:5432/microchat_users_test
        - NODE_ENV=${NODE_ENV}
        - TOKEN_SECRET=changeme
    depends_on:
        users-db:
            condition: service_healthy
    links:
        - users-db
